### ISSUE TITLE
Plugin echo instruction for oh my zsh

### ISSUE THREAD

**Issue by amaelftah** [robertzk/send.zsh#6]
after i executed the **echo command**  the line was at the bottom of script , while after i moved the line  like this screenshot the plugin worked 

![screenshot from 2018-01-13 23-25-54](https://user-images.githubusercontent.com/17250137/34910224-4f0b24ea-f8b9-11e7-873c-d7bbb7e504dc.png)

**Comment by robertzk** [comment]
Thanks @Te7a-Houdini ! Depending on your pre-existing .zshrc, you're right that the order when the plugin is appended to the plugin list may be important. Feel free to add this to the README if you can think of a good way to word it, but otherwise I'm going to close this issue.
